#!/bin/bash
# TrailCurrent First Login Setup
#
# Runs interactively when a user logs in and no .env file exists.
# Prompts for required configuration, auto-generates cryptographic secrets,
# writes .env, and starts all services.
#
# Triggered from .bash_profile — only runs once (until .env exists).

set -e

DEPLOY_DIR="$HOME"
ENV_FILE="$DEPLOY_DIR/.env"

# Only run if .env doesn't exist
if [ -f "$ENV_FILE" ]; then
    return 0 2>/dev/null || exit 0
fi

# Only run in interactive shells
if [ ! -t 0 ]; then
    return 0 2>/dev/null || exit 0
fi

echo ""
echo "============================================="
echo "  TrailCurrent Headwaters — First-Time Setup"
echo "============================================="
echo ""
echo "No configuration found. Let's set up your device."
echo "Cryptographic secrets will be auto-generated."
echo ""

# ── Helpers ──────────────────────────────────────────────────────────

prompt() {
    local var_name="$1"
    local prompt_text="$2"
    local default="$3"
    local value=""

    if [ -n "$default" ]; then
        read -rp "  $prompt_text [$default]: " value
        value="${value:-$default}"
    else
        while [ -z "$value" ]; do
            read -rp "  $prompt_text: " value
            [ -z "$value" ] && echo "    (required)"
        done
    fi
    eval "$var_name=\"\$value\""
}

prompt_password() {
    local var_name="$1"
    local prompt_text="$2"
    local value="" confirm=""

    while true; do
        read -srp "  $prompt_text: " value; echo ""
        if [ -z "$value" ]; then
            echo "    (required)"
            continue
        fi
        read -srp "  Confirm: " confirm; echo ""
        if [ "$value" = "$confirm" ]; then
            break
        fi
        echo "    Passwords don't match, try again."
    done
    eval "$var_name=\"\$value\""
}

# ── Collect configuration ────────────────────────────────────────────

TLS_CERT_HOSTNAME="headwaters.local"

echo "── MQTT Broker ──"
prompt MQTT_USERNAME "MQTT username" "trailcurrent"
prompt_password MQTT_PASSWORD "MQTT password"
echo ""

echo "── System Admin ──"
prompt_password ADMIN_PASSWORD "Admin password (for web UI)"
echo ""

# ── Generate secrets ─────────────────────────────────────────────────

echo "── Generating secrets ──"
ENCRYPTION_KEY=$(openssl rand -hex 32)
echo "  ENCRYPTION_KEY generated (32 bytes)"
echo ""

# ── Write .env ───────────────────────────────────────────────────────

cat > "$ENV_FILE" << EOF
# Generated by TrailCurrent first-login setup on $(date -I)

# MQTT Configuration
MQTT_BROKER_URL=mqtts://mosquitto:8883
MQTT_USERNAME=$MQTT_USERNAME
MQTT_PASSWORD=$MQTT_PASSWORD

# Encryption & Security
ENCRYPTION_KEY=$ENCRYPTION_KEY
ADMIN_PASSWORD=$ADMIN_PASSWORD

# API Configuration
API_PORT=3000
FRONTEND_PORT=443

# Database Configuration
DB_PATH=/app/data/invehicle.db
MONGODB_HOST=localhost
MONGODB_PORT=27017
MONGODB_DATABASE=trailcurrent

# Network Configuration
TLS_CERT_HOSTNAME=$TLS_CERT_HOSTNAME

# Environment
NODE_ENV=production
EOF

chmod 600 "$ENV_FILE"
echo "  .env written to $ENV_FILE"

# ── Create local_code .env with host-facing MQTT URL ─────────────────

if [ -d "$HOME/local_code" ]; then
    cp "$ENV_FILE" "$HOME/local_code/.env"
    sed -i "s|mqtts://mosquitto:|mqtts://${TLS_CERT_HOSTNAME}:|g" "$HOME/local_code/.env"
    echo "  local_code/.env written (host-facing MQTT URL)"

    # Copy CA cert for host-side scripts
    if [ -f "$HOME/data/keys/ca.pem" ]; then
        cp "$HOME/data/keys/ca.pem" "$HOME/local_code/ca.pem"
    fi
fi

# ── Install CA to system trust store ─────────────────────────────────

if [ -f "$HOME/data/keys/ca.crt" ]; then
    SYSTEM_CA="/usr/local/share/ca-certificates/trailcurrent-ca.crt"
    if [ ! -f "$SYSTEM_CA" ] || ! cmp -s "$HOME/data/keys/ca.crt" "$SYSTEM_CA"; then
        echo ""
        echo "── Installing CA certificate to system trust store ──"
        sudo cp "$HOME/data/keys/ca.crt" "$SYSTEM_CA"
        sudo update-ca-certificates > /dev/null 2>&1
        echo "  Done"
    fi
fi

# ── Start services ───────────────────────────────────────────────────

echo ""
echo "── Starting services ──"

cd "$DEPLOY_DIR"

# Start Docker Compose
echo "  Starting Docker containers..."
docker compose up -d --no-build --remove-orphans

# Restart systemd services now that .env exists
sudo systemctl restart cantomqtt.service 2>/dev/null || true
sudo systemctl restart discovery-mdns.service 2>/dev/null || true
sudo systemctl restart deployment-watcher.service 2>/dev/null || true
sudo systemctl restart os-settings.service 2>/dev/null || true
echo "  systemd services restarted"

echo ""
echo "============================================="
echo "  Setup complete!"
echo "============================================="
echo ""
echo "  Access the application at:"
echo "    https://$TLS_CERT_HOSTNAME"
echo ""
echo "  Docker status:"
docker compose ps --format "table {{.Name}}\t{{.Status}}" 2>/dev/null || docker compose ps
echo ""
echo "  Useful commands:"
echo "    docker compose logs -f          # Docker logs"
echo "    sudo journalctl -u cantomqtt -f # CAN-to-MQTT logs"
echo ""

# ── CA Certificate for browser trust ─────────────────────────────────

CA_CERT="$HOME/data/keys/ca.pem"
if [ -f "$CA_CERT" ]; then
    echo "============================================="
    echo "  IMPORTANT: Install CA Certificate"
    echo "============================================="
    echo ""
    echo "  Your browser needs the TrailCurrent CA certificate"
    echo "  to securely connect (HTTPS and WebSockets)."
    echo ""
    echo "  1. Copy the certificate below into a file on"
    echo "     your computer, e.g. trailcurrent-ca.pem"
    echo ""
    echo "  2. Install it as a trusted CA:"
    echo "     - Chrome/Edge: Settings → Privacy & Security"
    echo "       → Security → Manage certificates → Authorities"
    echo "       → Import → select trailcurrent-ca.pem"
    echo "     - Firefox: Settings → Privacy & Security"
    echo "       → Certificates → View Certificates → Authorities"
    echo "       → Import → select trailcurrent-ca.pem"
    echo "       → check \"Trust this CA to identify websites\""
    echo "     - macOS: Double-click the .pem file to add to"
    echo "       Keychain, then set to \"Always Trust\""
    echo "     - Windows: Rename to .crt, double-click → Install"
    echo "       → Local Machine → Trusted Root Certification"
    echo "       Authorities"
    echo ""
    echo "  ── Begin Certificate ──"
    echo ""
    cat "$CA_CERT"
    echo ""
    echo "  ── End Certificate ──"
    echo ""
fi
